-- An attached image and its destination now travel through one Send action.
-- Edit the existing picture paragraph in place: this is a merchant-visible
-- workflow correction, not a release-note section.

UPDATE public.help_articles
SET body = replace(
      body,
      $old$Mink never makes up an address for a picture: a layout proposal may use only pictures from your Media library, pictures already on the page it is changing, or a new picture Mink has just created for you. If you explicitly ask Mink to create a picture, say what it is for and describe the scene. Mink uses the intended placement to choose a suitable shape, makes one picture, saves it under <strong>Media</strong> and shows it to you with the wording screen readers will read out. If that same request names a page destination, such as a homepage hero or promotional banner, Mink also prepares the page change in the same response. You still review and approve that layout before it reaches your Website Builder draft, and publishing remains a separate step in Website Builder. Image generation costs AI credits; for a page redesign that does not require a new picture, Mink checks the images you already own first. A created picture is decoration, not a photograph of your goods, and Mink cannot set one as a product image. Every created picture carries an invisible marker identifying it as made by AI. You can also add your own under <strong>Media</strong>, or straight from the plus button in the chat when you have the file to hand.$old$,
      $new$Mink never makes up an address for a picture: a layout proposal may use only pictures from your Media library, pictures already on the page it is changing, an image you attached for that page, or a new picture Mink has just created for you. A file selected with the plus button appears as a removable preview card in your message. If your message clearly asks to use an attached image in a named storefront destination — for example a homepage carousel, hero, banner or gallery — Send saves your image under <strong>Media</strong> and Mink prepares the private page change in the same response. For a product promotion, Mink keeps your product photo intact and puts offer wording in the editable carousel text. You still review and approve the layout before it reaches your Website Builder draft, and publishing remains a separate step in Website Builder. For other image or document questions, open the preview card and review the extracted text before adding it to your message; that review does not save the original file. If you explicitly ask Mink to create a new decorative picture, say what it is for and describe the scene. Mink chooses a suitable shape, makes one picture, saves it under <strong>Media</strong> and shows it to you with the wording screen readers will read out. Image generation costs AI credits; for a page redesign that does not need a new picture, Mink checks the images you already own first. A created picture is decoration, not a photograph of your goods, and Mink cannot set one as a product image. Every created picture carries an invisible marker identifying it as made by AI.$new$
    ),
    updated_at = now()
WHERE slug = 'use-mink-ai-in-your-dashboard'
  AND status = 'published'
  AND body LIKE '%You can also add your own under <strong>Media</strong>, or straight from the plus button in the chat when you have the file to hand.%';
